version: 2.1


orbs:
  shellcheck: circleci/shellcheck@3.2.0


workflows:
  scripts:
    jobs:
      - shellcheck/check:
          name: shellcheck bash
          matrix:
            parameters:
              dir:
                - scripts/
                - src/scripts/
          shell: bash
          pattern: '^.*.sh$'
          exclude: SC2148

      - shellcheck/check:
          name: shellcheck bats
          shell: bats
          pattern: '^.*.bats$'